### PR TITLE
Update airvpn.md and surfshark.md for correct connection parameters

### PR DESCRIPTION
**Pull request by DrFrankensteinUK**
Hoping I have done this correctly, I plan on doing some additional amendments to try to help out where I have had people who are stuck setting up with other providers. 

As per EricBettanin  https://github.com/qdm12/gluetun-wiki/issues/28

Also made a small fix to the original files edits as had a trailing / on the compose section

Also submitted an overall improvement to the Surfshark page as you have to obtain the correct IP details otherwise the connection fails

### CODE REVIEW

**Comment by DrFrankensteinUK** [comment]
Learning here! - I have also make changes to the Surfshark page to provide clear details for how to obtain the correct connection settings for WireGuard and some other amendments to the page. Let me know any issues!

**Comment by DrFrankensteinUK** [comment]
@qdm12

Giving this a little nudge in case you missed the commit. Hopefully it's all above board.

**Comment by atticusmatticus** [comment]
This has worked for me. Thank you @DrFrankensteinUK! I hope this can be added to the official documentation soon as that would make it a lot easier to find.

**Comment by DrFrankensteinUK** [comment]
I have also documented the steps to generate correct AirVPN detail as this has also caught people out via my site/discord. I can submit them once the above gets approved.

**Comment by YuraT** [comment]
It may be worth mentioning that IPv6 does work with AirVPN if you follow the [advanced IPv6 setup](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/ipv6.md) guide.

Though that feature itself is "experimental" according to the doc.

**Comment by DrFrankensteinUK** [comment]
Hey thanks for the update, I just downloaded 3 different config files (Japan/Paris/Bulgaria) and all contain the same IP address for me and then different public keys. 

Just on the general subject of the provider specific pages. I get a ton of requests for help as people who are new to setting up a VPN in this manner quickly get lost on how to obtain the correct details etc. So would be good to get some more step-by-step instructions info into each page, so for someone new they can follow that and then the TLDR is for someone like me. 

I could crowdsource from my own Discord users as have a wide range of VPNs in use. Obviously the downside is making sure they stay current, but I suppose that's just part of the day to day with this stuff.

**Review by qdm12 — APPROVED** [review]

**Comment by qdm12** [comment]
I changed a bit your PR to focus on Surfshark, I've incorporated the Airvpn changes in separated commits (credits mentioned in the commit messages).

> I get a ton of requests for help as people who are new to setting up a VPN in this manner quickly get lost on how to obtain the correct details etc. So would be good to get some more step-by-step instructions info into each page

The thing is I don't really have a subscription with all the providers, so I can't really do a step by step for each. I do my best, for example with AirVPN, the [section on OpenVPN](https://github.com/qdm12/gluetun-wiki/blob/eb05fb39aee4e299f077796fb8660dafa4aaa3cb/setup/providers/airvpn.md#L36) is quite separate from Wireguard due to the many divergent steps involved (Setup your client key etc.)
I'm up for step by step guide through PRs though 😉 Ideally only text based, since the UI tend to change faster than text and a bad image is more confusing.

**Comment by DrFrankensteinUK** [comment]
Yeah cool, was looking to follow the formatting you have applied to the Surfshark as it keeps it simple enough to follow along. I have Shark and Air here. I will see what I can pull together via some of my Discord users and then do some pull requests as I confirm the steps are correct with them for their own providers.

**Comment by qdm12** [comment]
I'm retrying to keep it with the structure

1. copy-pasta-then-modify configs "TLDR" (merged usually, but sometimes separated for openvpn and wireguard if many steps are involved).
2. required variables - right now step-by-step is mentioned here on how to get them
3. optional variables
4. servers information
5. extra (like port forwarding)

**Pull request merged**
